export const apiQueries = [
  {
    era: "Prehistoric",
    titles: [
      "Lascaux Cave Paintings", "Hall of Bulls, Lascaux", "Chauvet Cave Horses", "Chauvet Cave Lions",
      "Altamira Bison Ceiling", "Bhimbetka Rock Dance Scene", "Tassili n’Ajjer Herd Scene",
      "Sulawesi Wild Cattle", "Pech Merle Spotted Horses", "Laas Gaal Cattle Figures",
      "Apollo 11 Stones", "Lion Man of Hohlenstein‑Stadel", "Venus of Willendorf",
      "Venus of Brassempouy", "Paleolithic hand stencils (Cueva de las Manos)",
      "Engravings at Les Combarelles", "Blombos Cave Ochre Plaque", "Drakensberg San Rock Art",
      "Newgrange Megalithic Carvings", "Hohle Fels Venus", "Dolní Věstonice Venus",
      "Magura Cave Dancers", "Cueva de las Manos guanacos", "Tadrart Acacus giraffes",
      "Kakadu Dreamtime Figures", "Luxmanda rock figures", "Serra da Capivara ritual scenes",
      "Bhimbetka cupule panels", "Font‑de‑Gaume bison panel", "Maros‑Pangkep therianthrope",
      "Leang Tedongnge pig scene", "Cosquer Cave horses", "El Castillo hand stencils",
      "Cap Blanc engraved frieze", "Venus of Lespugue", "Venus of Hohlestein",
      "Swabian Jura animal engravings", "Arcy‑sur‑Cure cave works", "Niaux cave bison",
      "Kents Cavern engravings", "Rouffignac mammoths", "Chauvet Lion Panel",
      "Altamira polychrome ceiling", "Venus of Moravany", "Venus of Savignano",
      "Engraved plaquettes at Grotte du Placard", "Bhimbetka bull hunting", "Laussel Venus relief",
      "Peckover cave symbols", "Grotte Chauvet Ox paintings", "Cave of El Juyo",
      "Die Kniessensee engravings", "Rouffignac unicorn figure", "Painted briquettes at Chauvet",
      "Monte Castillo stencils", "Les Trois Frères Sorcerer", "Ahrensburg culture carvings",
      "Trowel cave spiral motifs", "Camel rock art at Tassili", "Libyan desert cattle procession",
      "Red deer panel at Pech Merle", "Bison scene at Cap Blanc", "Grotte Cosquer marine fauna",
      "Apollo 11 stone zebra", "Grotte Chauvet rhino panel"
    ]
  },
  {
    era: "Ancient",
    titles: [
      "Palette of Narmer", "Fayum Mummy Portraits", "Bust of Nefertiti", "Akhenaten and Nefertiti relief",
      "The Dancers of Delphi fresco", "Villa of Mysteries fresco", "Alexander Mosaic (Pompeii)",
      "School of Athens fresco", "Frescoes of Pompeii House of the Vettii", "Laocoön and His Sons sculpture",
      "Winged Victory of Samothrace", "Aphrodite of Knidos", "Roman relief of Trajan’s Column",
      "Portrait of Septimius Severus family", "Pompeii Dionysus fresco (recent rediscovery)",
      "Villa Ariadne murals", "Egyptian Book of the Dead illustrations", "Ishtar Gate glazed bricks",
      "Assyrian lion hunt reliefs", "Minoan bull-leaping fresco",
      "Akrotiri frescoes (Thera)", "Roman fresco of Helen of Troy (Pompeii)",
      "Pompeii gladiator child drawing", "Hadrian right hand sculpture", "Pantheon interior decoration",
      "Temple of Zeus frieze in Olympia", "Statue of Zeus at Olympia", "Tomb of the Diver fresco",
      "Kushan Buddha sculptures", "Terracotta Army figures", "Trajan’s Column medallion",
      "Egyptian Amarna scenes", "Roman mosaic of Alexander and Darius",
      "Fayum portrait of young man", "Roman Alexandria fresco", "Nabataean rock art of Petra",
      "Roman villa mosaic of Orpheus", "Roman fresco of Helen at Pompeii",
      "Etruscan tomb frescoes in Tarquinia", "Dura-Europos synagogue murals",
      "Palmyra funerary reliefs", "Roman mosaic of the Battle of Issus",
      "Egyptian relief of Tutankhamun", "Roman cameo of Augustus", "Temple of Abu Simbel reliefs",
      "Mesopotamian Standard of Ur panels", "Egyptian Narmer palette", "Roman fresco Diana",
      "Greek red-figure amphora scenes", "Sarcophagus of Junius Bassus detail",
      "Roman panel from House of the Cryptoporticus", "Byzantine mosaic of Justinian at Ravenna",
      "Greek Parthenon frieze sections", "Egyptian murals at Theben", "Greek bronze Athena statue",
      "Roman fresco at Herculaneum", "Palmyra statue of the Lion of Al-lāt", "Roman wall painting of Nilotic scene",
      "Egyptian Athens Memphite sculpture", "Royal Game of Ur mosaic", "Gilgamesh plaque",
      "Roman mosaic of Hercules and the Lion", "Temple of Bacchus carving (Baalbek)", "Roman sarcophagus of the Seasons",
      "Egyptian Book of the Dead of Hunefer vignette"
    ]
  },
  {
    era: "Medieval",
    titles: [
      "Book of Kells illumination", "Lindisfarne Gospels", "Mérode Altarpiece", "Wilton Diptych",
      "Christ in Majesty (Christopher of Portland)", "Last Judgment Tympanum, Autun Cathedral",
      "Trinity icon by Andrei Rublev", "Ognissanti Madonna by Giotto", "Duccio Maestà panels",
      "Lorenzetti Allegory of Good Government", "Bayeux Tapestry scenes", "Ghent Altarpiece (partial panels)",
      "Scrovegni Chapel frescoes by Giotto", "Stained glass Sainte‑Chapelle windows",
      "Unicorn Tapestries", "Hildesheim Bernward Doors relief", "Westminster Psalter illuminations",
      "Coronation Gospels of Otto III", "Book of Hours of Jeanne d’Evreux",
      "Chartres Cathedral rose window", "Rohan Hours scenes", "Tree of Jesse window at Chartres",
      "Stavelot Triptych enamels", "Morgan Madonna statue", "Royal Psalter of St Denis",
      "Hungarian Annunciation panel", "Codex Westminster glosses", "Medieval mural of Mary and Child (Augsburg)",
      "Tympanum of Vézelay Abbey", "Cappella Palatina mosaics (Palermo)", "Codex Cambridge illuminations",
      "Altarpiece of Saint Ursula by Master of the Legend", "Berkeley Psalter miniatures",
      "Monreale Cathedral mosaics", "Saint John’s Bible folios", "Scandinavian staves carved panels",
      "Iona Book Celtic page", "Book of Jamshid Persian miniature", "Byzantine icon Aquila",
      "Vesalius illuminated anatomical drawings (medieval copies)", "Romanesque fresco of Christ Pantocrator",
      "Gospel of Otto III decorative canon tables", "Illuminated Bible of Saint Louis",
      "Triptych of the Annunciation by Fra Angelico", "Limbourg Brothers calendar pages",
      "Tres Riches Heures du Duc de Berry", "Book of Hours of Catherine of Cleves",
      "Altarpiece of the Crucifixion by Jan van Eyck", "Morgan Madonna statue (German)",
      "Pórtico da Gloria sculptural panels", "Cathedral of Santiago relief sculptures",
      "Saint‑Denis stained glass artist-labour scenes", "Gernrode Coronation Gospels pages",
      "Book of Durrow carpet page", "Fresco cycle in Arena Chapel",
      "Stavelot portable altar icons", "Codex Aureus of St Emmeram", "Byzantine Monastery frescoes of St Anthony",
      "Benedictional of St Æthelwold miniatures", "Oxford Apocalypse illustrations",
      "Lausanne Psalter initials", "Pictish carved stone cross panels"
    ]
  },
  {
    era: "Renaissance",
    titles: [
      "The Annunciation (Leonardo)", "Madonna of the Rocks", "The Birth of Venus",
      "The Last Supper", "David (Michelangelo sculpture)", "Primavera", "The School of Athens",
      "Saint George and the Dragon (Raphael)", "Portrait of a Man (da Vinci)",
      "Mona Lisa", "Creation of Adam", "Self‑Portrait van Gogh?? (error skip)", "Strozzi Altarpiece (Donatello?)",
      "Madonna del Granduca", "Vitruvian Man", "Bacchus (Michelangelo)", "The Last Judgment (Michelangelo)",
      "Venus (Botticelli)", "Saint Jerome in the Wilderness", "Bartolomeo Colleoni equestrian",
      "Portrait of Bia de’ Medici", "Isenheim Altarpiece", "Entombment of Christ", "The Temptation of Saint Anthony",
      "Lady with an Ermine", "Portrait of Cecilia Gallerani", "Assumption of the Virgin", "Pesaro Madonna",
      "Battle of San Romano", "Portrait of Michelangelo", "Portrait of Baldassare Castiglione",
      "Madonna with Child and Two Angels (Filippino Lippi)", "David by Donatello", "Madonna of the Goldfinch",
      "The Feast of the Gods", "Giuliano de' Medici Portrait", "Venus and Mars", "Baptism of Christ (Verrocchio & da Vinci)",
      "Adoration of the Magi (Botticelli)", "Portrait of Pope Julius II", "Saint Mark (Donatello)",
      "Madonna of Chancellor Rolin", "Portrait of a Lady (da Messina)", "Doni Tondo", "Saint Catherine of Alexandria",
      "Portrait of Giovanna Tornabuoni", "The Baptism of Christ (Piero della Francesca)", "St George (Raphael)",
      "The Four Apostles", "The Harvesters", "Madonna and Child with Two Angels", "The Battle of Cascina",
      "The Tempest (Giorgione)", "Deposition (Pontormo)", "Portrait of Cosimo I de’ Medici",
      "Madonna of the Chair", "Baldacchino di San Pietro bronze canopy", "Limoniadi frescoes (Masaccio?)",
      "The Vision of Saint Jerome", "Portrait of Eleonora Gonzaga", "Madonna della Misericordia"
    ]
  },
  {
    era: "Baroque",
    titles: [
      "The Night Watch", "Las Meninas", "The Elevation of the Cross", "Judith Beheading Holofernes",
      "The Milkmaid", "The Calling of Saint Matthew", "The Ecstasy of Saint Teresa", "Bacchus",
      "David with the Head of Goliath (Caravaggio)", "Apollo and Daphne", "The Inspiration of Saint Matthew",
      "Las Hilanderas", "The Triumph of the Immaculate Conception", "The Rape of the Sabine Women",
      "Surrender of Breda", "Girl with a Pearl Earring", "Portrait of Innocent X", "An Experiment on a Bird in the Air Pump",
      "The Feast of St Nicholas", "The Elevation of the Cross (Rubens)", "Saint Serapion",
      "Venus at her Mirror", "Saint Peter Released from Prison", "A Woman Holding a Balance",
      "Still Life with Flowers", "Las Meninas by Velázquez", "The Martyrdom of Saint Philip",
      "Judith Slaying Holofernes by Gentileschi", "Saint Jerome Writing", "Self‑Portrait Rembrandt",
      "Night Watch", "Return of the Prodigal Son", "Alexander at the Battle of Granicus",
      "Ecstasy of Saint Cecilia (duques)", "Allegory of the Planets and Continents", "The Feast of Herod",
      "Judith and her Maidservant", "Deposition from the Cross", "Charles I at the Hunt",
      "Portrait of Louis XIV", "The Denial of Saint Peter", "Samson and Delilah", "The Calling of Saint Matthew",
      "Las Meninas (again?) skip duplicates", "The Black Paintings by Goya (late baroque??)",
      "Flower Still Life (Snyders)", "The Triumph of Galatea", "The Infanta Margarita Teresa in a Blue Dress",
      "The Temptation of Saint Anthony (Brouwer)", "Self‑Portrait as the Allegory of Painting",
      "The Young Martyr", "Portrait of Lord Philip", "The Entombment", "The Family of Darius before Alexander",
      "The Capture of Bahia", "The Swing (framed earlier) skip", "The Love of the Golden Idol", "The Celebrated Spring Feast in the Villa d’Este"
    ]
  },
  {
    era: "Rococo",
    titles: [
      "The Swing (Fragonard)",
      "Pilgrimage to Cythera",
      "The Embarkation for Cythera",
      "Madame de Pompadour",
      "The Toilette of Venus",
      "Let Them Eat Cake",
      "The Progress of Love",
      "Portrait of Madame de Pompadour",
      "Return from Cythera",
      "Dance at Bougival",
      "The Breakfast Scene",
      "Young Woman Reading",
      "The Love Letter",
      "Madame de Pompadour at Her Tambour Frame",
      "Girl Chasing a Butterfly",
      "Children Playing",
      "The Meeting",
      "Les Confidences",
      "Allegory of Love",
      "Marriage Contract",
      "The Courting Couple",
      "The First Family",
      "Cupid a Captive",
      "The Harlot’s Progress – book of engravings",
      "A Visit to Cupid",
      "Portrait of the Artist",
      "Beach Scene at Trouville",
      "The Abduction of Europa",
      "Pan and Syrinx",
      "Love’s Young Dream",
      "Girl Playing with a Dog",
      "Peloton in Aveyron",
      "Conversation Under the Arbor",
      "Serenade Under the Lamp",
      "Fête Galante with Figures",
      "Louise Élisabeth Vigée Le Brun Self Portrait",
      "Portraites de Louis XV",
      "Venus at the Toilet",
      "The Meeting of Marie‑Antoinette",
      "Courting Scene",
      "Summer (The Four Seasons series)",
      "The Bouquet",
      "Scene in a Park",
      "The Letter",
      "Portrait of Countess",
      "A Young Girl Reading",
      "Children with a Goat",
      "A Young Girl Reclining",
      "Fêtes de la Cour",
      "Young Couple in a Park",
      "Music Lesson",
      "Love‑in‑a‑Park",
      "Allegory of Spring",
      "The Music Party",
      "Elegant Couple at the Ball",
      "Couple in a Swing",
      "Girl with a Letter",
      "Seaside Frolic",
      "Boating on the Seine",
      "At the Opera Box",
      "A Garden at Versailles",
      "The Eclipse of Love",
      "A Family at Their Devotions",
      "Lovers Beneath a Tree",
      "River Party",
      "The Orange Seller"
    ]
  },
  {
    era: "Neoclassicism",
    titles: [
      "Oath of the Horatii",
      "Death of Socrates",
      "Napoleon Crossing the Alps",
      "The Death of Marat",
      "Portrait of Madame Récamier",
      "The Intervention of the Sabine Women",
      "Pauline Borghese as Venus",
      "The Dance of the Hours",
      "Belisarius Begging for Alms",
      "Cornelia, Mother of the Gracchi",
      "The Young Napoleon in the Moorish Habit",
      "Andromache Mourning Hector",
      "The Apotheosis of Homer",
      "Napoleon in His Coronation Robes",
      "Portrait of Madame Tallien",
      "The Tennis Court Oath",
      "Portrait of Joséphine",
      "Cupid and Psyche",
      "Self‑Portrait in the Atelier",
      "Portrait of Madame Récamier",
      "The Sabine Women",
      "Endymion",
      "Belisarius Sick",
      "Napoleon Visiting the Pesthouse at Jaffa",
      "Portrait of Elisa Bonaparte",
      "The Educator",
      "The Vestal Virgin Tuccia",
      "Portrait of a Roman Lady",
      "Washington Crossing the Delaware",
      "Self‑Portrait Piranesi",
      "Ignatius of Loyola Adoring the Divine Name",
      "Portrait of Princess Caroline",
      "The Apotheosis of Washington",
      "The Romans in their Decay",
      "Horatius Cocles Defending the Bridge",
      "The Funeral of Atala",
      "Napoleon on the Throne",
      "The Continence of Scipio",
      "Portrait of Talleyrand",
      "Napoleon Visiting the Plague Victims in Jaffa",
      "The Emperor Napoleon in His Study",
      "Jeanne‑Catherine‑Le Maupied‑de‑Lordat",
      "The Oracle of Delphi",
      "Madame Geoffrin",
      "The Dead Sacrifice of Abraham",
      "Portrait of Grand Duchess Natalia",
      "Napoleon and the Imperial Eagle",
      "Cupid and Psyche",
      "Cornelia, Mother of the Gracchi",
      "Napoleon as Mars the Peacemaker",
      "Portrait of Pope Pius VII",
      "The Football Players (Ingres)",
      "Portrait of Eugène de Beauharnais",
      "Empedocles on Mount Etna",
      "Portrait of Joséphine de Beauharnais",
      "The Death of Hyacinth",
      "Landscape with Apollo",
      "The Conquest of the Sabine Women",
      "Portrait of Napoleon in Crowning Robes",
      "Dido and Aeneas",
      "The Martyrdom of Saint Stephen",
      "Portrait of Madame Recamier (detail)",
      "Saturn Devouring His Son",
      "Portrait of Emeric Essex Vidal",
      "The Emperor Napoleon"
    ]
  },
  {
    era: "Romanticism",
    titles: [
      "The Raft of the Medusa",
      "Liberty Leading the People",
      "The Third of May 1808",
      "Wanderer Above the Sea of Fog",
      "The Nightmare",
      "The Hay Wain",
      "The Slave Ship",
      "The Fighting Temeraire",
      "Saturn Devouring His Son",
      "The Death of Sardanapalus",
      "Monk by the Sea",
      "The Massacre at Chios",
      "Snow Storm: Hannibal and His Army Crossing the Alps",
      "The Fighting Temeraire",
      "The Lady of Shalott",
      "The Isle of the Dead",
      "Queen Victoria in Highland Dress",
      "The Eruption of Vesuvius",
      "The Heart of the Andes",
      "The Gulf Stream",
      "Rain, Steam and Speed",
      "Napoleon on the Saint‑Bernard Pass",
      "The Ox Bow",
      "Rome, from Mount Aventine",
      "Liberty on the Barricades",
      "The Flying Dutchman",
      "Scenes from Don Juan",
      "Dante and Virgil in Hell",
      "The Temeraire",
      "The Haywain",
      "Shipwreck of the Minotaur",
      "Pegwell Bay",
      "The Monk by the Sea",
      "Caprice of the Artist",
      "Dream of the Fisherman's Wife",
      "Der Wanderer",
      "Ghent Altarpiece detail (romantic reinterpretation)",
      "The Wanderer Above the Sea of Fog",
      "Rainy Day by Adolf Schreyer",
      "The Cadaver Synod Scene",
      "Morpheus in a Dream",
      "Titan’s War",
      "Solitude",
      "Detail from Shipwreck mural",
      "Fatalism",
      "Portrait of Shelley",
      "Portrait of Lord Byron",
      "Italian Sunset Landscape",
      "Venetian Canal in Moonlight",
      "Poetic Aesthetic Scene",
      "The Burning of Sodom",
      "A European Castle Ruin",
      "Dulcinea and Don Quixote",
      "Study after Nature",
      "The Devils (Delaroche)",
      "Portret of Rus‑Ukrainian Noblewoman",
      "The Death of Chatterton",
      "The Corsican Brothers",
      "Titon and Selena",
      "Portrait of Charlotte Corday",
      "Portrait of Schubert",
      "Ancient Ruins at Ophelia",
      "The Flood by Gustave Doré"
    ]
  },
  {
    era: "Realism",
    titles: [
      "The Gleaners",
      "The Stone Breakers",
      "Burial at Ornans",
      "Olympia",
      "A Burial at Ornans",
      "The Gross Clinic",
      "Women Ironing",
      "Third‑Class Carriage",
      "The Iron Rolling Mill",
      "The Potato Eaters",
      "Jean Valjean in Prison",
      "The Veteran in a New Field",
      "The Bellelli Family",
      "The Social Origins of Modern Art",
      "The Haymakers",
      "The Gleaners",
      "A Corner of the Table",
      "The Gross Clinic",
      "The Third‑Class Carriage",
      "Nude Maja",
      "Whistler’s Mother",
      "Morning in a Pine Woods",
      "The Blind Woman",
      "A Burial at Ornans",
      "The Fighting Temeraire (realist reinterpretation)",
      "Portrait of Zola",
      "The Dinner Horn",
      "Claude Monet's early realism",
      "The Anthropologists Fieldwork",
      "Gleaners at Dawn",
      "Approaching Storm",
      "Woman with a Fan",
      "After the Flood",
      "Portrait of Madame X",
      "The Stone Breakers",
      "Reclining Nude",
      "The Wanderer",
      "The Cemetery",
      "The Recruit",
      "The Widow",
      "Self‑Portrait with Pipe",
      "The Woodcutter",
      "Fresh from the Oven",
      "The Fighting Temeraire (again skip)",
      "The Vermilion Ram",
      "The Pouring Water",
      "The Sands in Sun",
      "Early Morning in the Fields",
      "The Bathers",
      "Conversation Piece",
      "Still Life with Apples",
      "The Milkmaid (realist version)",
      "Woman Ironing",
      "La Promenade",
      "Miss La La at the Cirque",
      "Portrait of a Woman Reading",
      "The Horse Fair",
      "Rouen Cathedral (early realism)",
      "The Accolade",
      "The Peasants’ Meal",
      "Harvest",
      "The Psychiatric Patient",
      "The Bunch of Flowers",
      "The Tailor",
      "The Straw Hat",
      "The Joy of Life"
    ]
  },
  {
    era: "Impressionism",
    titles: [
      "Water Lilies",
      "Impression, Sunrise",
      "The Luncheon on the Grass",
      "Ballet Rehearsal",
      "The Boating Party",
      "The Dance Class",
      "Woman with a Parasol",
      "Rouen Cathedral series",
      "Parade de cirque",
      "La Grenouillère",
      "Sunrise on the Seine",
      "Boulevard des Capucines",
      "The Artist’s Garden",
      "The Grainstack (Effect of Snow)",
      "Woman in the Garden",
      "The Red Boats at Argenteuil",
      "Woman with a Parasol – Madame Monet",
      "Regatta at Argenteuil",
      "Poppy Field near Argenteuil",
      "Breakfast on the Grass",
      "The Card Players",
      "Camille Monet in Green Dress",
      "Le Moulin de la Galette",
      "The Beach at Trouville",
      "Field of Tulips",
      "Coquelicots",
      "The Gare Saint‑Lazare",
      "Vienna at Night",
      "Woman with Umbrella",
      "Houses of Parliament",
      "Sunset at Montmajour",
      "Waterloo Bridge",
      "Snow at Argenteuil",
      "The Japanese Footbridge",
      "Haystacks, Sunrise",
      "Portrait of Claude Monet",
      "Garden at Sainte‑Adresse",
      "The Seine at Asnières",
      "Interior, Woman Braiding Her Hair",
      "Study of Agapanthus",
      "Two Sisters (On the Terrace)",
      "On the Bank of the Seine",
      "Spring",
      "Lady in a Yellow Bus",
      "Vétheuil in Winter",
      "The Artist’s House at Argenteuil",
      "Woman with a Parasol (detail)",
      "Luncheon of the Boating Party",
      "The Path through the Corn",
      "Sunset in Venice",
      "Venetian waterway",
      "La Promenade",
      "Poppy Meadow",
      "The Cliff Walk at Pourville",
      "Portrait of Madame Sisley",
      "Workmen on the Shore",
      "Windmill at Zaandam",
      "Waterlily Pond"
    ]
  },
  {
    era: "Post-Impressionism",
    titles: [
      "Starry Night",
      "The Bedroom",
      "Vision After the Sermon",
      "Sunday Afternoon on La Grande Jatte",
      "Where Do We Come From? What Are We?",
      "Mont Sainte‑Victoire",
      "The Yellow Christ",
      "A Sunday on La Grande Jatte",
      "Still Life with Apples",
      "The Card Players (Cézanne)",
      "The Red Vineyard",
      "Van Gogh’s Chair",
      "Self‑Portrait with Bandaged Ear",
      "The Night Café",
      "Paul Gauguin in Tahiti",
      "Portrait of Madame Matisse",
      "The Basket of Apples",
      "Saint‑Rémy Hospital View",
      "Sunflowers",
      "Portrait of Dr Gachet",
      "Peasant and Peasant Woman",
      "Still Life with Blue Apples",
      "Self‑Portrait Roulin’s Coiffure",
      "Young Peasant Woman",
      "Van Gogh’s Sunflowers",
      "Still Life with Fruit Dish",
      "Cézanne’s Bathers",
      "Félix Fénéon Portrait",
      "Women with Hats",
      "The Large Bathers",
      "The Dream (Rousseau)",
      "The Circus",
      "The Yellow House",
      "The Blue Nude",
      "La Siesta",
      "The Lovers (Klimt)",
      "Portrait of Adele Bloch‑Bauer",
      "Landscape at Auvers",
      "Self‑Portrait with Straw Hat",
      "Still Life with Bottle and Fruit",
      "Interior with Attendants (Toulouse‑Lautrec)",
      "The Waltz",
      "Portrait of Henri de Toulouse‑Lautrec",
      "Autumn Landscape",
      "Isle of Joy",
      "Portrait of Igor Stravinsky",
      "Gauguin’s Mahana no Atua",
      "Cézanne’s Montagne Sainte‑Victoire",
      "Van Gogh’s Irises",
      "Houses at Auvers",
      "Portrait of Dr Rey",
      "Self‑Portrait as a Painter",
      "Bathers by the Sea",
      "Still‑Life with Fruit — head of a woman",
      "Portrait of the Artist’s Mother",
      "The White Horse",
      "Paul Signac Grand Canal"
    ]
  },
  {
    era: "Modern",
    titles: [
      "The Persistence of Memory",
      "The Scream",
      "Les Demoiselles d’Avignon",
      "Guernica",
      "The Red Studio",
      "Composition VIII",
      "Nude Descending a Staircase",
      "Broadway Boogie Woogie",
      "The Weeping Woman",
      "Blue Nude",
      "Black Square",
      "Impression, Sunrise (modern reinterpretation)",
      "The Lovers II",
      "American Gothic",
      "Fountain (Duchamp)",
      "Broadway Boogie Woogie",
      "Campbell’s Soup Cans",
      "The Treachery of Images",
      "Composition II in Red, Blue and Yellow",
      "The Garden of Earthly Delights (20th‑century re‑reading)",
      "The Bride Stripped Bare",
      "Les Demoiselles d’Avignon",
      "The Yellow Cow",
      "Portrait of Dora Maar",
      "Blue Horse I",
      "Woman I",
      "No. 5, 1948",
      "Green Stripe",
      "Broadway Boogie Woogie",
      "La Muse Endormie",
      "The False Mirror",
      "Wham!",
      "Black Iris",
      "Girl before a Mirror",
      "Number 31, 1950",
      "The Piano Lesson",
      "Woman with Flowered Hat",
      "Portrait of Luis Fco. Lázaro",
      "Elegy for the Spanish Republic",
      "Broadway Boogie‑Woogie",
      "Blue Poles",
      "Three Musicians",
      "Horse Trotting",
      "Woman with Hand Mirror",
      "Composition with Red, Yellow, Blue",
      "The Lovers III",
      "Sky Cathedral",
      "Migrant Mother",
      "The Treachery of Images"
    ]
  },
  {
    era: "Contemporary",
    titles: [
      "Untitled (Portrait)",
      "Balloon Dog",
      "For the Love of God",
      "Infinity Mirror Room",
      "Sky Mirror",
      "The Weather Project",
      "Portrait of Barack Obama",
      "Girl with Balloon",
      "My Bed",
      "The Physical Impossibility of Death",
      "Rain Room",
      "Cloud Gate",
      "Girl with Headscarf (Banksy)",
      "The Clock (Elmgreen & Dragset)",
      "Untitled Film Still #21",
      "David: The Head of Goliath",
      "Love Fountain",
      "The Dinner Party",
      "Untitled (L.A. Women)",
      "In Praise of Shadows",
      "Heavenly Crescents",
      "Black Star Press",
      "Balloon Girl",
      "Shibboleth",
      "The Weather Project (again skip duplicates)",
      "Portrait of Pasolini",
      "I Am Not a Man Without Hearts",
      "Your Rainbow Panorama",
      "Her Secret is Patience",
      "Ship of Tolerance",
      "Herb & Dorothy Archive",
      "Dust Breeding",
      "Crying Boy",
      "Untitled (Cornell Boxes)",
      "The Physical Impossibility of Death in the Mind of Someone Living",
      "The Bean (Cloud Gate)",
      "Girl in the Red Dress",
      "Nike Air VaporMax (Art Installation)",
      "Infinity Mirrored Room",
      "Untitled (Portrait of Ross in L.A.)",
      "Stephen Hawking’s Spoon",
      "Portrait of George W. Bush",
      "The Dinner Party Place Setting",
      "Balloon Dog (Blue)",
      "Sky Mirror (Red)",
      "The Weather Project (again)…",
      "Portrait of Michelle Obama",
      "My Bed (Tracey Emin)",
      "Cloud Gate (Chicago)",
      "Girl with Balloon (Banksy)"
    ]
  }
];


export const fetchArtworksByTitles = async (
  titles: string[],
  era: string,
  setLoadingStatus: (msg: string) => void
) => {
  const artworks = [];

  for (const title of titles) {
    try {
      setLoadingStatus(`Fetching: "${title}"...`);

      const searchUrl = `https://api.artic.edu/api/v1/artworks/search?q=${encodeURIComponent(title)}&query[term][is_public_domain]=true&fields=id,title,artist_display,date_display,medium_display,image_id&limit=1`;
      const response = await fetch(searchUrl);
      const data = await response.json();

      const artwork = data?.data?.[0];
      if (artwork && artwork.image_id) {
        artworks.push({
          id: artwork.id,
          title: artwork.title,
          artist: artwork.artist_display || "Unknown Artist",
          period: era,
          year: artwork.date_display || "Date unknown",
          image: `https://www.artic.edu/iiif/2/${artwork.image_id}/full/843,/0/default.jpg`,
          description: artwork.medium_display || "Medium unknown",
          creditLine: "Art Institute of Chicago",
          style: '',
          classification: 'Painting',
          subjects: []
        });
      }
    } catch (err) {
      console.warn(`Failed to fetch "${title}"`, err);
    }
    await new Promise(res => setTimeout(res, 1000)); 
  }

  return artworks;
};

export const fetchAllEraArtworks = async (
  setLoadingStatus: (msg: string) => void,
  perEra: number = 6
) => {
  const allArtworks = [];

  for (const era of apiQueries) {
    const titles = era.titles.slice(0, perEra);
    const eraArtworks = await fetchArtworksByTitles(titles, era.era, setLoadingStatus);
    allArtworks.push(...eraArtworks);
  }

  return allArtworks;
};

export const getFallbackArtworks = () => [
  {
    id: 0,
    title: "Fallback Art",
    artist: "Fallback Artist",
    image: "https://via.placeholder.com/400x300.png?text=Fallback+Art",
    period: "Modern",
    year: "2020",
    description: "Placeholder art for fallback.",
    creditLine: "Generated",
    style: '',
    classification: 'Painting',
    subjects: []
  }
];
